### ISSUE TITLE
Derived metric specification 

### ISSUE THREAD

**Issue by brnorris03** [HPCL/autoperf#13]
Allow users to specify derived metrics anywhere by giving the full path name in the configuration file

**Comment by xdai** [comment]
How about let the user specify a directory where autoperf should look for derived metric definition? If not specified, default directory will be used (i.e. fall back to current behavior).

**Comment by brnorris03** [comment]
Yes, that would work.

**Comment by xdai** [comment]
Mark as "Closed". Feel free to reopen if it doesn't work.
